version: '3'
services:
  customer-service:
    image: customer-service:latest
    build:
      context: ./customer-service
    ports:
      - "9091:9091"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - im-network

  account-service:
    image: account-service:latest
    build:
      context: ./account-service
    ports:
      - "5432:5432"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - im-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_account_service
    ports:
      - "5433:5432"
    networks:
      - im-network

networks:
  im-network:
    driver: bridge
