version: '3'
services:
  customer-service:
    image: customer-service:latest  # Your customer-service image
    build:
      context: ./customer-service  # Directory of the customer service project
    ports:
      - "8081:8081"  # Expose customer-service on port 8081
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/


  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: post
    ports:
      - "5432:5432"
