server:
    port: 9089

spring:
    application:
        name: transaction-service
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
        generate-ddl: false
    datasource:
        username: user
        password: password
        url: jdbc:postgresql://localhost:5433/db_transaction_service

    cloud:
        openfeign:
            client:
                config:
                    default:
                        logger-level: FULL
                    account-service:
                        url: http://localhost:9095/api/v1/accounts
    kafka:
        producer:
            bootstrap-servers: localhost:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer


