server:
    port: 8083

spring:
    application:
        name: transaction-service
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
        generate-ddl: false
    datasource:
        username: user
        password: password
        url: jdbc:postgresql://db:5432/db_transaction_service

    cloud:
        openfeign:
            client:
                config:
                    default:
                        logger-level: FULL
                    account-service:
                        url: http://account-service:9092/api/v1/accounts

