server:
    port: 8081

spring:
    application:
        name: customer-service
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        generate-ddl: false

    datasource:
        username: sa
        password: password
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
        driverClassName: org.h2.Driver
