server:
    port: 1001

spring:
    application:
        name: customer-service
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
        generate-ddl: false
    datasource:
        username: user
        password: password
        url: jdbc:postgresql://localhost:5433/db_im_interview

