server:
    port: 8081

spring:
    application:
        name: customer-service
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
        generate-ddl: false
    datasource:
        username: postgres
        password: postgres
        url: jdbc:postgresql://localhost:5433/im_database
    cloud:
      discovery:
          enabled: true
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:9090/eureka/
