server:
    port: 9090
    address: 0.0.0.0
spring:
    application:
        name: discovery-service
    cloud:
        config:
            enabled: false
eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
    instance:
        hostname: discovery-service
