server:
    port: 9092

spring:
    application:
        name: customer-service
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
        generate-ddl: false
    datasource:
        username: user
        password: password
        url: jdbc:postgresql://db:5433/db_account_service

    cloud:
        openfeign:
            client:
                config:
                    default:
                        logger-level: FULL
                    customer-service:
                        url: http://customer-service:5432/api/v1/customers

